from setuptools import Command

class bdist_wheel(Command):
    def get_tag(self) -> tuple[str, str, str]: ...
    def finalize_options(self) -> None: ...
    def initialize_options(self) -> None: ...
    def run(self) -> None: ...
