name: Wheels

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_wheels:
    name: ${{ matrix.version[1] }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      fail-fast: false
      matrix:
        buildplat:
        - [ubuntu-20.04, manylinux_x86_64]
        version:
        - ["3.7", "cp37"]
        - ["3.8", "cp38"]
        - ["3.9", "cp39"]
        - ["3.10", "cp310"]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_BUILD: ${{ matrix.version[1] }}-${{ matrix.buildplat[1] }}
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BUILD_VERBOSITY: 3
          CIBW_BEFORE_BUILD: bash {project}/tools/install_cpp_deps.sh "${{ matrix.version[0] }}"
          CIBW_ENVIRONMENT:
            EIGEN3_INCLUDE_DIR="$HOME/miniconda/include/eigen3"
            LIBINT_INCLUDE_DIR="$HOME/miniconda/include"
            LIB_DIR="$HOME/miniconda/lib"
          CIBW_REPAIR_WHEEL_COMMAND: auditwheel repair -w {dest_dir} {wheel} -v

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
